version: '3.9'
services:
  cacttus-core-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=artistDb'
    ports:
      - '5437:5432'